# configuration from https://rudd-o.com/linux-and-free-software/switching-an-usb-load-on-or-off-using-the-sinilink-xy-wfusb-and-esphome

esphome:
  name: relay-switch
  friendly_name: Relay Switch

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: info

# Enable Home Assistant API
api:
  encryption:
    key: x

ota:
  password: x

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip: 
    static_ip: 192.168.xxx.xxx
    gateway: 192.168.xxx.xxx
    subnet: 255.255.255.0    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Relay-Switch Fallback Hotspot"
    password: "5QCl6LD2Tgue"
    ap_timeout: 3min

captive_portal:

button:
- platform: restart
  name: Restart
  entity_category: diagnostic
  icon: mdi:restart
- platform: safe_mode
  name: Safe mode restart
  entity_category: diagnostic
  icon: mdi:restart-alert

# Blue LED
status_led:
  pin:
    number: GPIO16

switch:
  # Relay
  - platform: gpio
    id: relay
    pin: GPIO5

  # Green LED
  - platform: gpio
    pin: GPIO14
    id: green_led
    inverted: true # start on

  # Switch template to link relay and green LED states
  # LED is on when relay is off
  - platform: template
    id: relay_switch
    name: Switch
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
        - switch.turn_on:
            id: green_led
        - switch.turn_on:
            id: relay
    turn_off_action:
        - switch.turn_off:
            id: green_led
        - switch.turn_off:
            id: relay

# Button
binary_sensor:
  - platform: gpio
    id: relay_switch_button
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: "relay_switch"
