alias: Lutron Example
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.lutron_z3_1brl_controller
    attribute: rotate_right
    id: rotate-right
  - platform: state
    entity_id:
      - sensor.lutron_z3_1brl_controller
    attribute: rotate_left
    id: rotate-left
  - platform: state
    entity_id:
      - sensor.lutron_z3_1brl_controllera
    attribute: action_type
  - platform: template
    value_template: >-
      {% set rotate =
      (state_attr('sensor.lutron_z3_1brl_controller','transition_time')|int(0))
      == 2 and (state_attr('sensor.lutron_z3_1brl_controller','level')|int(0)) >
      0 %}

      {% set minclick =
      (state_attr('sensor.lutron_z3_1brl_controller','transition_time')|int(0))
      == 2 and (state_attr('sensor.lutron_z3_1brl_controller','level')|int(0))
      == 0 %}

      {% set levelcombo =
      ((state_attr('sensor.lutron_z3_1brl_controller','level')|string) +
      (state_attr('sensor.lutron_z3_1brl_controller','debounce_level')|string))
      %}

      {% set double = (levelcombo in ['2550', '0255', '00', '255255']) and
      (click or minclick) and
      state_attr('sensor.lutron_z3_1brl_controller','debounce_diff') < 1 %}

      {% set levelcombo =
      ((state_attr('sensor.lutron_z3_1brl_controller','level')|string) +
      (state_attr('sensor.lutron_z3_1brl_controller','debounce_level')|string))
      %}

      {% if double %}

      {% endif %}
condition: []
action:
  - if:
      - condition: and
        conditions:
          - condition: trigger
            id: rotate-right
          - condition: numeric_state
            entity_id: sensor.lutron_z3_1brl_controller
            attribute: rotate_right
            above: 0
    then:
      - service: input_number.increment
        data: {}
        target:
          entity_id: input_number.lutron_example
  - if:
      - condition: and
        conditions:
          - condition: trigger
            id: rotate-left
          - condition: numeric_state
            entity_id: sensor.lutron_z3_1brl_controller
            attribute: rotate_left
            above: 0
    then:
      - service: input_number.decrement
        data: {}
        target:
          entity_id: input_number.lutron_example
mode: queued
max: 20
